name: Release
on: workflow_dispatch
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest # TODO needed right?
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main
            - run: |
                  git config user.name ${{ github.event.sender.login }}
                  git config user.email ${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com
            - run: |
                  # echo foo >> README.md
                  git fetch ${{ github.ref }}
                  git merge --squash ${{ github.ref }}
                  git status
                  git commit -am "auto merge commit"
                  git push
