# Motivation:
# * External PRs can't run all checks (because secret is not available)
# * External PRs often need adjustment but feature branch can have "edits from
# maintainers" disabled.
name: Release
on: workflow_dispatch
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest # TODO needed right?
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main
            - run: |
                  cat << EOF
                  ${{ toJson(github) }}
                  EOF
            - run:
                  # TODO can this be a requirement (i.e. check has been run on this branch)
                  # (might need github token)
                  # also alternative https://github.com/octokit/request-action
                  # (but yeah, sets output to string, has to use fromjson() github expr, seems a
                  # bit cumbersome?)
                  curl https://api.github.com/repos/${{ github.repository }}/commits/heads/${{ github.ref_name }}/check-suites?app_id=15368 | jq --exit-status '.check_suites[0].conclusion=="success"'
            - run: |
                  git config user.name ${{ github.actor }}
                  git config user.email ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
            - run: |
                  git remote -v
                  git fetch origin ${{ github.ref_name }}
                  git merge --squash --ff-only origin/${{ github.ref_name }}
                  # git status
                  # git diff --staged
                  git commit -am "auto merge commit"
                  VERSION=0.0.1 # TODO read from file
                  git tag $VERSION
                  git push origin main $VERSION
